1) بعد از بلاک های catch

2) در صورت داشتن catch مربوط به آن استثنا catch می شود
و در غیر اینصورت توسط catch مربوطه در توابع قبلی catch می شود

3) شی exception به توابع قبلی منتقل و هر کدام که catch مربوط به آن را داشته باشند آن Exception را دریافت می کنند

4) بعد از throw شی Exception به دلیل دریافت نشدن استثنا برنامه terminate  می شود

5)Exception ایجاد شده در catch در توابع قبلی به دنبال catch  مربوط به می گردد در صورت نبودن catch مربوطه برنامه terminate  می شود و این موضوع ربطی به تایپ catch ایجاد کننده استثنا ندارد